# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ipcv',
                'doc_host': 'https://abdelhamednour.github.io',
                'git_url': 'https://github.com/abdelhamednour/ipcv',
                'lib_path': 'ipcv'},
  'syms': { 'ipcv.evaluation': {},
            'ipcv.failures': {},
            'ipcv.geometry': {},
            'ipcv.image_processing': {},
            'ipcv.localization': {},
            'ipcv.localization_workflow': {},
            'ipcv.observability': {},
            'ipcv.service': {},
            'ipcv.workflow': {}}}
